import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { makeRequest, getData } from '../lib/api';
import axios from 'axios';

export default function Home({ listings = [] }) {
  // const [listings, setListings] = useState([]);
  // useEffect(() => {
  //   axios.get('api/etsy').then((response) => {
  //     console.log(response);
  //     setListings(response.data.results);
  //   });
  //   // shop id is 23419135
  // }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-2xl font-bold">Items</h1>
        {listings.map((item, index) => (
          <p key={index}>
            <a href={item.url}>{item.title}</a>
          </p>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  // Run API calls in parallel
  const [listings] = await Promise.all([getData()]);

  return {
    props: { listings },
    revalidate: 1,
  };
}
